### ISSUE TITLE
Source file online

### ISSUE THREAD

**Issue by bijancot** [scen-git/Covid-19_notify#6]
Om,

gimana kalau file di dalam folder `src/*` dibuat online aja. Jadi kalau mau install dia `curl` langsung dari server siapa terserah, 

wdyt?
Thx

**Comment by JustHumanz** [comment]
hemm mending curl langsung ke install.sh nya aja terus awto git clone dan install dependency

`curl https://raw.githubusercontent.com/scen-git/Covid-19_notify/master/install.sh | bash`

**Comment by bijancot** [comment]
kalo pake `curl https://raw.githubusercontent.com/scen-git/Covid-19_notify/master/install.sh | bash` dependencynya langsung ambil dari `raw.githubusercontent.com` ?

**Comment by JustHumanz** [comment]
gak,tetep git clone 
kalau langsung wget Covid-19.desktop & Covid-19_notify.sh dan ditaruh ke ~/.config/autostart bakal gak mau awto start karena `echo Exec=$HOME/.config/autostart/Covid-19_notify.sh >> src/Covid-19.desktop` gak ke eksekusi

**Comment by bijancot** [comment]
kalo wget sebelum `echo Exec=$HOME/.config/autostart/Covid-19_notify.sh >> src/Covid-19.desktop` ?

**Comment by JustHumanz** [comment]
bisa,di wget dulu terus di echo langsung ke ~/.config/autostart/Covid-19.desktop

**Comment by JustHumanz** [comment]
lihat [5a1e9f2](https://github.com/scen-git/Covid-19_notify/commit/5a1e9f2dd876706c654825b73dcab3b5ba5d3de9#diff-3fbb47e318cd8802bd325e7da9aaabe8)

**Comment by bijancot** [comment]
ok om, baru mau tak edit wkwk. Thx fix my issue.

Thx
